### ISSUE TITLE
Script crashes when taking a backup of a large database

### ISSUE THREAD

**Issue by mlaitinen** [avoinsystems/odoo-backup-restore-s3#3]
```
Traceback (most recent call last):
  File "backup.py", line 186, in <module>
    backup(**vars(args))
  File "backup.py", line 70, in backup
    data = conn.dump(odoo_master_password, database, 'zip')
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1316, in parse_response
    p.feed(data)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 438, in feed
    self._parser.Parse(data, 0)
  File "/usr/src/python/Modules/pyexpat.c", line 468, in EndElement
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 687, in end
    return f(self, "".join(self._data))
MemoryError
```

The database in question was successfully backed up using the web interface. It was 330 megabytes.

The same error occurs when restoring a large backup (but this time in the odoo container):
```
2017-01-28 16:14:54,959 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 152, in wsgi_xmlrpc
    params, method = xmlrpclib.loads(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1136, in loads
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
  File "/usr/lib/python2.7/xmlrpclib.py", line 824, in end
    return f(self, join(self._data, ""))
  File "/usr/lib/python2.7/string.py", line 312, in join
    return sep.join(words)
MemoryError
```

Idea: since the HTTP POST methods work, create an option to use them instead of XML-RPC

**Comment by mlaitinen** [comment]
Solution: use the HTTP protocol (`--protocol=HTTP`) to take large dumps.
